export async function ethan(interaction){
    await interaction.deferReply({ ephemeral: false });
    const picops = [
        "./ethan/ethan.png",
        "./ethan/ethan1.png",
        "./ethan/ethan2.png",
        "./ethan/ethan3.png",
        "./ethan/ethan4.png",
        "./ethan/ethan5.png",
        "./ethan/ethan6.png",
        "./ethan/ethan7.png",
        "./ethan/ethan8.png",
        "./ethan/ethan9.png",
    ]

    const messagePrompts=[
        'Enough Sucky\nTime for Fucky',
        'Why would god give you hands if they weren`t meant for beating women?',
        'My brain is so fractalized',
        'My fingers smell like crayons',
        'I have the mental power of two 50 cal machine guns',
        'I feel like I can do it, how hard can it be? (no fap)',
        'Your fingers will be Lara croft in my bum',
        'Sleep is a subjective concept',
        'Iʼm open 24/7 Waffle House ass. Iʼll give you the syrup you need. You want jemima, Iʼll give jemima. Iʼm cumming jemima everywhere',
        'I canʼt focus Iʼm running veggie tales in my head.',
        'If I get robbed at gun point Iʼm gonna be really upset',
        'Get off Emily. Itʼs time for sucky not fucky.',
        'I wanna watch waterworld extended edition',
        'I ate her afterbirth',
        'What would we do without fire? What would we use to burn down abortion clinics?',
        'If a cop tries to arrest us Iʼll reach for the gun. I wonʼt let him take my lacroix.',
        'Kpop makes me rapey',
        'Just ate a piece of sushi off his plate with his mouth and snorted',
        'I have 6 title 9 cases against me. Me and my dog keep fucking.',
        'My dog is tr$nsgender.',
        'I just came to college to get PUSSY',
        'Iʼd fuck anything bro. Iʼd fuck a fence post at this point.',
        'They wanna fuck my rolls',
        'What is chick-fil-a?',
        'Just cuz I like fruit doesn`t mean I`m drunk you asshole',
        'I`m gonna tickle your little ballsack',
        'Do you think my grandma had sex with a velociraptor?',
        'I`m the epitome of strength wisdom intelligence etc',
        'I want casey to buy me Taco Bell then fuck me in the ass',
        'What if the characters of shrek were in this movie (pirates of the Caribbean)',
        'Give me the succ grandma',
        'Whatʼs your favorite world of Warcraft expansion? (To a room full of girls)',
        'Iʼm prob$bly big enough to rape people now',
        'Senior year is gonna be such a meme. Iʼm gonna walk into class tomorrow shit my pants and walk out.',
        'Girls canʼt burp thatʼs why god gave them queefing',
        'Iʼm gonna kill someone at the party',
        'Wait tomorrowʼs 9/11? YES! I hate Americans!',
        'Itʼs not rape grandma!',
        'Iʼll hammer your clit',
        'I donʼt want nicotine because Iʼve been holding in a poop',
        'Iʼm gonna make this kid cum. Iʼm making a gay kid cum',
        'Idk what time I went to bed last night.',
        'Was it before or after I raped you?',
        'If you donʼt bring her back and fuck her so I can listen and jerk off Iʼll be so pissed',
        'Wait I watched this video of a cop getting shot itʼs dope as fuck',
        'You guys wanna join my protest? Weʼre gonna protest that coconuts classify as mammals',
        '(watching himself) This makes me wanna cum dude',
        'Do you think there are people who jerk off to 9/11 footage?',
        'Can you even strangle a dog',
        'How come thereʼs no news about isis anymore? Did trump get rid of isis',
        'Sheʼs gonna peg me',
        'They get into your head like little cockroaches. Just kidding Iʼm not sexist',
        'Paul the only reason you like the rain is because you live in your room in an anime universe',
        'Would you rather hear the thumping of my music or the thumping of my cock',
        'I can feel the nicotine and the caffeine coursing through my veins',
        'If we watch a movie today Iʼm gonna cream',
        'Time to push like my grandmas push up bra',
        'Iʼm rich. I have a lot of money and girls wanna FUCK ME',
        'You look like goomba from Mario but Iʼll still fuck',
        'Iʼm gonna projectile scrum all over your pussy',
        'I swear to god Iʼm gonna rape every fucking dog I see',
        'Hey if you ever need pods let me buy them. If I buy six packs of pods from k-mart I get a free juul',
        'Your juul hits like a motherfucker. When they hunted the juul pods on the Sahara desert yours was the alpha. Stop juul poaching',
        'I honestly just signed up for this class for the anime',
        'My leg hair will keep me warm',
        'You did drive here you lying succubus (to Sierra)',
        'Its always small business Saturday when you fuck a hooker.',
        'Wow! Thanks for the hilarious meme! I really appreciate it!'
    ]
    
    let messageChoice= Math.floor(Math.random()*messagePrompts.length);
    let message = messagePrompts[messageChoice];
    let picChoice= Math.floor(Math.random()*picops.length);
    let pic= picops[picChoice]
    return void interaction.editReply({ files: [pic], content: message  });
}
